// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: person.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Teach_Teaching_FullMethodName = "/teach/teaching"
)

// TeachClient is the client API for Teach service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TeachClient interface {
	Teaching(ctx context.Context, in *Teacher, opts ...grpc.CallOption) (*Teacher, error)
}

type teachClient struct {
	cc grpc.ClientConnInterface
}

func NewTeachClient(cc grpc.ClientConnInterface) TeachClient {
	return &teachClient{cc}
}

func (c *teachClient) Teaching(ctx context.Context, in *Teacher, opts ...grpc.CallOption) (*Teacher, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Teacher)
	err := c.cc.Invoke(ctx, Teach_Teaching_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeachServer is the server API for Teach service.
// All implementations should embed UnimplementedTeachServer
// for forward compatibility.
type TeachServer interface {
	Teaching(context.Context, *Teacher) (*Teacher, error)
}

// UnimplementedTeachServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTeachServer struct{}

func (UnimplementedTeachServer) Teaching(context.Context, *Teacher) (*Teacher, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Teaching not implemented")
}
func (UnimplementedTeachServer) testEmbeddedByValue() {}

// UnsafeTeachServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeachServer will
// result in compilation errors.
type UnsafeTeachServer interface {
	mustEmbedUnimplementedTeachServer()
}

func RegisterTeachServer(s grpc.ServiceRegistrar, srv TeachServer) {
	// If the following call pancis, it indicates UnimplementedTeachServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Teach_ServiceDesc, srv)
}

func _Teach_Teaching_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Teacher)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeachServer).Teaching(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Teach_Teaching_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeachServer).Teaching(ctx, req.(*Teacher))
	}
	return interceptor(ctx, in, info, handler)
}

// Teach_ServiceDesc is the grpc.ServiceDesc for Teach service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Teach_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "teach",
	HandlerType: (*TeachServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "teaching",
			Handler:    _Teach_Teaching_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "person.proto",
}
